### PR TITLE
Update interaction widget display

### PR DESCRIPTION
**Pull request by ThibNach**
Use user tags to filter slots selection of smartobject component when using `WaitUseSmartObjectGameplayBehaviorWithSmartObjectComponent`

check suboptions of interactable actor to check if at least one interaction is triggerable before displaying the widget

- - -
This change is [Reviewable](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/268)

### CODE REVIEW

**Review by TheEmidee — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/268)* status: all files reviewed, 1 unresolved discussion (waiting on @MaxDaniels, @ThibNach, and @VectorGamez)

___
*[`Source/GameBaseFramework/Private/GAS/Tasks/GBFAT_WaitUseSmartObjectGameplayBehavior.cpp` line 69 at r1](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/268#-Nz3adP74YKCBLzT8Djk:-Nz3adP74YKCBLzT8Djl:b-vn50ug) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/75e83bd84bb0d39c6226b88f6eb8cd441d5dcc18/Source/GameBaseFramework/Private/GAS/Tasks/GBFAT_WaitUseSmartObjectGameplayBehavior.cpp#L69)):*
> ```cpp
> }
> 
> UGBFAT_WaitUseSmartObjectGameplayBehavior * UGBFAT_WaitUseSmartObjectGameplayBehavior::WaitUseSmartObjectGameplayBehaviorWithSmartObjectComponent( UGameplayAbility * owning_ability, USmartObjectComponent * smart_object_component, EGBFATSmartObjectComponentSlotSelection slot_selection, FSmartObjectRequestFilter user_tags_filter )
> ```

construct this in the function, set the UserTags with the tags from the actor running the task, and allow the caller to specify the activitytags and behavior definitions

**Review by ThibNach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/268)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @MaxDaniels, @TheEmidee, and @VectorGamez)

___
*[`Source/GameBaseFramework/Private/GAS/Tasks/GBFAT_WaitUseSmartObjectGameplayBehavior.cpp` line 69 at r1](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/268#-Nz3adP74YKCBLzT8Djk:-Nz3nCHWDI48PLOLsshk:b-896fix) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/75e83bd84bb0d39c6226b88f6eb8cd441d5dcc18/Source/GameBaseFramework/Private/GAS/Tasks/GBFAT_WaitUseSmartObjectGameplayBehavior.cpp#L69)):*
<details><summary><i>Previously, TheEmidee (Michael Delva) wrote…</i></summary><blockquote>

construct this in the function, set the UserTags with the tags from the actor running the task, and allow the caller to specify the activitytags and behavior definitions
</blockquote></details>

Done.

**Review by Frickerson — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/268#-:-Nz3qL-k7Ck5J_hmW24B:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @MaxDaniels and @TheEmidee)

**Review by TheEmidee — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/268#-:-Nz3xLeD-R7ma-YzbgRk:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MaxDaniels)

**Review by TheEmidee — DISMISSED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/268)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MaxDaniels)

**Review by Frickerson — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/268)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @MaxDaniels and @TheEmidee)

**Review by TheEmidee — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/268)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MaxDaniels)

**Pull request merged**
