### PR TITLE
EquipmentInstance attachement

### PR DESCRIPTION
**Pull request by ThibNach**
use definition's itemsocket or use offset definition's transform if no socket to attach the equipment

- - -
This change is [Reviewable](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/269)

### CODE REVIEW

**Review by TheEmidee — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/269)* status: all files reviewed, 2 unresolved discussions (waiting on @Fr0oZzFred, @MaxDaniels, @ThibNach, and @VectorGamez)

___
*[`Source/GameBaseFramework/Private/Equipment/GBFEquipmentInstance.cpp` line 80 at r1](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/269#-NzD-J9B0Dq9XrszkS4H:-NzD-J9B0Dq9XrszkS4I:b-kydsqs) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/db3b356b6c4123f9610a6fc9f5e0e0e7d58c2399/Source/GameBaseFramework/Private/Equipment/GBFEquipmentInstance.cpp#L80)):*
> ```cpp
> }
> 
> void UGBFEquipmentInstance::SetEquipmentActorTransform( AActor * equipment_actor, const FGBFEquipmentActorToSpawn & actor_to_spawn, USceneComponent * attach_target )
> ```

instead of passing `actor_to_spawn`, pass the `ItemSocket`, the `AttachSocket` and the `AttachTransform`
___
*[`Source/GameBaseFramework/Private/Equipment/GBFEquipmentManagerComponent.cpp` line 122 at r2](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/269#-NzDQRDG6tY09Do2MQAf:-NzDQRDG6tY09Do2MQAg:bso1fwc) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/f2cac261dcb10feca858115af5a53b2e6d706751/Source/GameBaseFramework/Private/Equipment/GBFEquipmentManagerComponent.cpp#L122)):*
> ```cpp
>         if ( auto * owning_pawn = new_entry.Instance->GetPawn() )
>         {
>             auto * attach_target = owning_pawn->FindComponentByClass< USkeletalMeshComponent >();
> ```

if ( auto ... )

**Review by ThibNach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/269)* status: all files reviewed, 2 unresolved discussions (waiting on @Fr0oZzFred, @MaxDaniels, @TheEmidee, and @VectorGamez)

___
*[`Source/GameBaseFramework/Private/Equipment/GBFEquipmentInstance.cpp` line 80 at r1](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/269#-NzD-J9B0Dq9XrszkS4H:-NzDRn0j6zpU97V6SYZm:b-896fix) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/db3b356b6c4123f9610a6fc9f5e0e0e7d58c2399/Source/GameBaseFramework/Private/Equipment/GBFEquipmentInstance.cpp#L80)):*
<details><summary><i>Previously, TheEmidee (Michael Delva) wrote…</i></summary><blockquote>

instead of passing `actor_to_spawn`, pass the `ItemSocket`, the `AttachSocket` and the `AttachTransform`
</blockquote></details>

Done.
___
*[`Source/GameBaseFramework/Private/Equipment/GBFEquipmentManagerComponent.cpp` line 122 at r2](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/269#-NzDQRDG6tY09Do2MQAf:-NzDS-vS9ye64oQhMHLm:b-896fix) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/f2cac261dcb10feca858115af5a53b2e6d706751/Source/GameBaseFramework/Private/Equipment/GBFEquipmentManagerComponent.cpp#L122)):*
<details><summary><i>Previously, TheEmidee (Michael Delva) wrote…</i></summary><blockquote>

if ( auto ... )
</blockquote></details>

Done.

**Review by TheEmidee — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/269)* status: all files reviewed, 1 unresolved discussion (waiting on @Fr0oZzFred, @MaxDaniels, @ThibNach, and @VectorGamez)

___
*[`Source/GameBaseFramework/Private/Equipment/GBFEquipmentInstance.cpp` line 79 at r3](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/269#-NzDh07-DSZD_TCVZTWU:-NzDh07-DSZD_TCVZTWV:b43elvq) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/9bc6e93f8b03cd0589e307570b33157116ad6c78/Source/GameBaseFramework/Private/Equipment/GBFEquipmentInstance.cpp#L79)):*
> ```cpp
> }
> 
> void UGBFEquipmentInstance::SetEquipmentActorTransform( AActor * equipment_actor, const FName item_socket, const FName attach_socket, const FTransform attach_transform, USceneComponent * attach_target )
> ```

the transform must be passed by const reference to avoid a copy (The names can be left like that because they are basically integers)

**Review by Frickerson — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/269#-:-NzRmBm11K430X8ODDEd:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Fr0oZzFred, @MaxDaniels, and @ThibNach)

**Review by ThibNach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/269)* status: all files reviewed, 1 unresolved discussion (waiting on @Fr0oZzFred, @MaxDaniels, and @TheEmidee)

___
*[`Source/GameBaseFramework/Private/Equipment/GBFEquipmentInstance.cpp` line 79 at r3](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/269#-NzDh07-DSZD_TCVZTWU:-NzRr6vd88uKgH-jG5oi:b-896fix) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/9bc6e93f8b03cd0589e307570b33157116ad6c78/Source/GameBaseFramework/Private/Equipment/GBFEquipmentInstance.cpp#L79)):*
<details><summary><i>Previously, TheEmidee (Michael Delva) wrote…</i></summary><blockquote>

the transform must be passed by const reference to avoid a copy (The names can be left like that because they are basically integers)
</blockquote></details>

Done.

**Review by TheEmidee — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/269#-:-NzSGd5tBJjyyZVlzv7j:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Fr0oZzFred and @MaxDaniels)

**Pull request merged**
